### ISSUE TITLE
CC316152007TW did not get rigth result

### ISSUE THREAD

**Issue by DenisSokoloff** [kevin3747118/Logistic#1]
I see you use captcha solver before but then found direct solutions
Can you check current script to track CC316152007TW for example
I did not get track result now

**Comment by kevin3747118** [comment]
Hi Denis, are u using my program now ?

**Comment by DenisSokoloff** [comment]
No, I try my php script with your JSON params

` 
        $vo = "EB500100";
        $q  = "query5";

        $fields = [];
        $fields["header"]                         = [];
        $fields["header"]["InputVOClass"]         = "com.systex.jbranch.app.server.post.vo.".$vo."InputVO";
        $fields["header"]["TxnCode"]              = $vo;
        $fields["header"]["BizCode"]              = $q;
        $fields["header"]["StampTime"]            = true;
        $fields["header"]["SupvPwd"]              = "";
        $fields["header"]["TXN_DATA"]             = [];
        $fields["header"]["SupvID"]               = "";
        $fields["header"]["CustID"]               = "";
        $fields["header"]["REQUEST_ID"]           = "";
        $fields["header"]["ClientTransaction"]    = true;
        $fields["header"]["DevMode"]              = false;
        $fields["header"]["SectionID"]            = "esoaf";

        $fields["body"]                         = [];
        $fields["body"]["MAILNO"]               = $track_number;
        $fields["body"]["pageCount"]            = 10;
`

But I think Taiwan Post fix it and remove track w/o captcha.
Can you check your current params to track now?

**Comment by kevin3747118** [comment]
@DenisSokoloff Sure, I will try with my parameters. Btw may I know why u need those information 😂 ?

**Comment by kevin3747118** [comment]
@DenisSokoloff Hey Denis, this parameters is for this [site](http://postserv.post.gov.tw/pstmail/main_mail.html), and I can not retrieve any info from your package  No. Which site are u using ?

**Comment by DenisSokoloff** [comment]
Ok, thanks, I use other way to track with captcha solver now
